export const INGREDIENTS = {
  GET_ALL_INGREDIENTS : 'GET_ALL_INGREDIENTS',
  GET_ALL_FORMULATIONS : 'GET_ALL_FORMULATIONS',
  SAVE_USER_PROFILE: 'SAVE_USER_PROFILE',
  SELECT_FORMULATION: 'SELECT_FORMULATION',
  ADD_INGREDIENT: 'ADD_INGREDIENT',
  UPDATE_INGREDIENT: 'UPDATE_INGREDIENT',
  DELETE_INGREDIENT: 'DELETE_INGREDIENT',
  SAVE_INGREDIENTS: 'SAVE_INGREDIENTS'
}


export const COMMON = {
  	SERVER_REQUEST: 'SERVER_REQUEST',
  	SERVER_FAILURE: 'SERVER_FAILURE',
  	SERVER_SUCCESS: 'SERVER_SUCCESS',
}
